### PR TITLE
Include deckType.js to fix index.html

### PR DESCRIPTION
**Pull request by harrisi**
#9 breaks `index.html`. This fixes that by including `deckType.js`.

### CODE REVIEW

**Comment by einaregilsson** [comment]
Thanks. Didn't actually think anyone was using this project, I haven't thought about it in years! But it has 103 forks, so I guess someone is. Are you making a game?

**Comment by harrisi** [comment]
Yes, I'm implementing a game called [Ride the bus](https://en.wikipedia.org/wiki/Ride_the_bus) for my girlfriend's birthday next week. The repo is private for now, but it'll be made public next week, hopefully.

If you don't mind me asking, you said you haven't thought about this project in years, but it seems like you're still actively using it on cardgames.io. Do you mean you're just not using this open source version of the library, in favor of a private version you have?

Also I just wanted to say thanks! I also hadn't thought of this in years, but was happy to find it again since it significantly speeds up this birthday present.

**Comment by einaregilsson** [comment]
Ok, first of all, awesome birthday present 🙂

> [...] seems like you're still actively using it on cardgames.io. Do you mean you're just not using this open source version of the library, in favor of a private version you have?

Actually I'm not using it at all, it's just the same card images. I made cards.js because I wanted to make a better version of what I had on cardgames.io, but then I never really finished it and never started using it myself.

**Comment by harrisi** [comment]
Interesting. Well I'm glad you got it to where you did at least. I think I'll be able to get everything working in time, and a huge part of that is because you put this up.

Thanks again!

**Pull request merged**
