### PR TITLE
Missing offset entries for the two joker suits results in jokers rend…

### PR DESCRIPTION
**Pull request by jptoomey**
…ering as facedown red card image. Since the Jokers are the first card position in the heart and spade rows in the cards.png file, mapping these two "suits" to hearts and spades allows the image mapping to pick up the right joker cards when opt.blackJoker or opt.redJoker are set to true.

### CODE REVIEW

**Comment by einaregilsson** [comment]
Thanks! This project isn't really active, haven't touched it in over 5 years, but nice if someone can still use it :)

**Comment by jptoomey** [comment]
Thanks for merging and for open sourcing your work. It’s enough of a start to change my project from “something I would never have time to complete” to “something that might actually be doable.” Appreciate it much!

Thanks,
--Joe




> Thanks! This project isn't really active, haven't touched it in over 5 years, but nice if someone can still use it :)

**Comment by einaregilsson** [comment]
Glad you could use it. Post a link to your game here if you finish it and put it up somewhere :)

**Comment by jptoomey** [comment]
Thanks, will do!

**Pull request merged**
